import {
  ControlPlaneRoleIdSelection,
  EpochMillis,
  HostTokenId,
  HostTokenName,
  HostTokenPermissionSelection,
  PrincipalId,
} from "@ptools/host-authorization/contracts";
import { Schema } from "effect";

/**
 * HTTP path parameters identifying the Principal whose global roles are being
 * administered.
 *
 * `ControlPlaneAdministrationGroup` uses this schema to decode
 * `:principalId` on the role-replacement route before the handler constructs
 * the host-authorization package's domain input. This identifies the mutation
 * target, not the authenticated assigner; middleware supplies the assigner's
 * verified identity separately so a caller cannot author that trusted fact.
 */
export const ControlPlanePrincipalPath = Schema.Struct({
  principalId: PrincipalId,
});
export type ControlPlanePrincipalPath = Schema.Schema.Type<
  typeof ControlPlanePrincipalPath
>;

/**
 * Public HTTP body for replacing a Principal's complete Control Plane role
 * assignment.
 *
 * The payload contains only the caller-authored role selection. The target
 * Principal comes from `ControlPlanePrincipalPath`, while the authenticated
 * assigner comes from admission. The HTTP handler combines those values into
 * the domain mutation input; neither identity can be forged through this body.
 * An empty `roleIds` selection remains valid here, with final-administrator
 * protection enforced atomically by the owning access store.
 */
export const ReplaceControlPlaneRolesHttpPayload = Schema.Struct({
  roleIds: ControlPlaneRoleIdSelection,
});
export type ReplaceControlPlaneRolesHttpPayload = Schema.Schema.Type<
  typeof ReplaceControlPlaneRolesHttpPayload
>;

/**
 * HTTP path parameters locating one Host-bound credential for management.
 *
 * The revoke route decodes both `:hostId` and `:credentialId` rather than
 * accepting a globally addressed token ID. Admission uses `hostId` to resolve
 * the caller's Host authority, and the token service receives both values so
 * persistence cannot accidentally revoke a credential outside that Host.
 * Authentication and revoker identity are deliberately absent and are supplied
 * from trusted request middleware.
 */
export const HostCredentialPath = Schema.Struct({
  hostId: Schema.NonEmptyString,
  credentialId: HostTokenId,
});
export type HostCredentialPath = Schema.Schema.Type<typeof HostCredentialPath>;

/**
 * Caller-authored HTTP body describing a new Host token.
 *
 * The caller chooses the display name, delegated permission snapshot, and
 * optional expiry. `Schema.OptionFromOptionalKey` converts an omitted expiry to
 * Effect `Option` for host-side code while preserving an ordinary optional JSON
 * field at the HTTP boundary. The route supplies the Host ID and admission
 * supplies the verified issuer; token ID, secret, hash, and audit timestamps are
 * generated by the trusted token service and therefore cannot be submitted in
 * this payload.
 */
export const IssueHostTokenHttpPayload = Schema.Struct({
  name: HostTokenName,
  grantedPermissions: HostTokenPermissionSelection,
  expiresAtEpochMs: Schema.OptionFromOptionalKey(EpochMillis),
});
export type IssueHostTokenHttpPayload = Schema.Schema.Type<
  typeof IssueHostTokenHttpPayload
>;
