/**
 * Runtime semantic port for registered-Host and Principal-access persistence.
 *
 * This is the one capability request-time callers (the `Authorization`
 * service, host-api admission middleware, platform handlers) use to read and
 * mutate host access. It deliberately contains only operations a caller can
 * choose to perform: each method is one caller-driven verb, documented by one
 * module under `contracts/hostAccessOperations/`. Inputs are schema-backed
 * operation values; successes are the domain values callers actually need
 * rather than transport-style single-field result wrappers.
 *
 * Platform adapters supply this service's Layer over their own persistence
 * (Node SQLite, Cloudflare Durable Object storage, in-memory test stores).
 * They decode persistence values into `RegisteredHost`, `HostMemberAccess`,
 * and `HostRole`. `HostRoleId` is the shared logical UUID, not a projection of
 * a database primary key; an adapter may encode it as text, native UUID data,
 * or 16 RFC-ordered bytes and keep surrogate keys privately. Input/output
 * identity agreement and mutation atomicity are service laws exercised by the
 * shared platform contract suite.
 *
 * Built-in role installation is deliberately NOT a method here. Seeding has no
 * caller and no caller-authored input: the package owns the complete catalog
 * (`BuiltInHostRoles`, with UUIDv5 IDs derived from the immutable canonical
 * names), so the only platform obligation is to insert those exact rows during
 * platform initialization, before the first host is created. Keeping that step
 * off the port means init-only mutations are never exposed to request-time
 * callers, and tests pin that no seed operation exists on this service.
 *
 * Because seeded IDs are derived deterministically — not generated by the
 * database — later operations reference them directly: `createOwnedHost`
 * resolves `BuiltInHostRoles.owner.roleId` inside its atomic
 * Host/membership/assignment operation, and future catalog migrations target
 * the same stable UUIDs. This port therefore needs no seed operation, seed
 * binding, or platform-generated default-role reference.
 */
import { Context, Effect } from "effect";
import {
  type CreateHostMembershipError,
  type CreateHostMembershipInput,
  type CreateOwnedHostError,
  type CreateOwnedHostInput,
  type CreatedOwnedHost,
  type ListHostRolesError,
  type ListHostRolesInput,
  type ListPrincipalHostsError,
  type ListPrincipalHostsInput,
  type ListRegisteredHostsError,
  type ListRegisteredHostsInput,
  type ReplaceMembershipRolesError,
  type ReplaceMembershipRolesInput,
  type GetHostRoleError,
  type GetHostRoleInput,
  type GetRegisteredHostError,
  type GetRegisteredHostInput,
  type ResolvePrincipalHostAccessError,
  type ResolvePrincipalHostAccessInput,
} from "../contracts/hostAccessOperations/index.js";
import type { HostMemberAccess } from "../contracts/hostMemberAccess.js";
import type { HostRole } from "../contracts/hostRole.js";
import type { RegisteredHost } from "../contracts/registeredHost.js";

/** Platform-owned registered-Host, role, and Principal-access capability. */
export class HostAccessStore extends Context.Service<
  HostAccessStore,
  {
    readonly getRegisteredHost: (
      input: GetRegisteredHostInput,
    ) => Effect.Effect<RegisteredHost, GetRegisteredHostError>;

    readonly createOwnedHost: (
      input: CreateOwnedHostInput,
    ) => Effect.Effect<CreatedOwnedHost, CreateOwnedHostError>;

    readonly listPrincipalHosts: (
      input: ListPrincipalHostsInput,
    ) => Effect.Effect<ReadonlyArray<RegisteredHost>, ListPrincipalHostsError>;

    readonly listRegisteredHosts: (
      input: ListRegisteredHostsInput,
    ) => Effect.Effect<ReadonlyArray<RegisteredHost>, ListRegisteredHostsError>;

    readonly resolvePrincipalHostAccess: (
      input: ResolvePrincipalHostAccessInput,
    ) => Effect.Effect<HostMemberAccess, ResolvePrincipalHostAccessError>;

    readonly createMembership: (
      input: CreateHostMembershipInput,
    ) => Effect.Effect<HostMemberAccess, CreateHostMembershipError>;

    readonly replaceMembershipRoles: (
      input: ReplaceMembershipRolesInput,
    ) => Effect.Effect<HostMemberAccess, ReplaceMembershipRolesError>;

    readonly getHostRole: (
      input: GetHostRoleInput,
    ) => Effect.Effect<HostRole, GetHostRoleError>;

    readonly listHostRoles: (
      input: ListHostRolesInput,
    ) => Effect.Effect<ReadonlyArray<HostRole>, ListHostRolesError>;
  }
>()("@ptools/host-authorization/HostAccessStore") {}
